### ISSUE TITLE
Save image cache for a client

### ISSUE THREAD

**Issue by reidelkins** [apify/apify-client-python#150]
I want to speed up consecutive calls that use the same actor. There are places on the website that describe a build cache for the docker containers but say they are only available on the API.

**Comment by fnesveda** [comment]
Hi,

if you're referring to the Docker build cache, that caches the Docker image layers between two successive Actor builds, that is turned on by default, and you can use it in the API client through the `use_cache` argument in the [`ActorClient.build()` method](https://docs.apify.com/api/client/python/reference/class/ActorClient#build).

If you'd like to cache the Docker image of an Actor between successive calls of the Actor on the servers where the Actors are executed, that's not always possible and there is no way to control that. When you run an Actor, we cache its Docker image on the executing server, and when you run the Actor again, we try to allocate it to the same server, which should have its image cached. This is not always possible, however (perhaps the server is full and the Actor has to run on a different server, or the image was evicted from the cache because it was not executed for a long time), and the Actor image has to be pulled again.

Does that answer your question?

**Comment by fnesveda** [comment]
Closing as I think this is an invalid issue, feel free to reopen if you don't agree.
